=== DAMnificado/marcas/Trabajo/trabajodtd.dtd
<!ELEMENT concurso (informacion, participantes)>
<!ATTLIST concurso id NMTOKEN #REQUIRED>
<!ELEMENT informacion (sede, datos)>
          <!ELEMENT sede (direccion, localidad, provincia)>
          <!ELEMENT datos (fechafin, edicion)>
          
                <!ELEMENT direccion (#PCDATA)>
                <!ELEMENT localidad (#PCDATA)>
                <!ELEMENT provincia (#PCDATA)>
                <!ELEMENT fechafin (#PCDATA)>
                <!ELEMENT edicion ANY>
                
<!ELEMENT participantes (participacion+)>
          <!ELEMENT participacion (grupo | solista )>
          <!ATTLIST participacion cod ID #REQUIRED>
                <!ELEMENT grupo (integrante+)>
                                                 <!ATTLIST grupo
                                                   tipo CDATA #REQUIRED
                                                   nombre CDATA #REQUIRED>
                 <!ELEMENT integrante (nombre, apellido, dni, lider?)>
                                              <!ATTLIST integrante instrumento CDATA #IMPLIED>
                                         <!ELEMENT nombre (#PCDATA)> 
                                         <!ELEMENT apellido (#PCDATA)> 
                                         <!ELEMENT dni (#PCDATA)>
                                         <!ELEMENT lider EMPTY>
                <!ELEMENT solista (integranteS)>
                          <!ELEMENT integranteS (nombreS, apellidoS, dniS)>
                                                      <!ATTLIST integranteS instrumento CDATA #IMPLIED>
                                                      <!ATTLIST integranteS tipo CDATA #REQUIRED>
                                          <!ELEMENT nombreS (#PCDATA)> 
                                          <!ELEMENT apellidoS (#PCDATA)> 
                                          <!ELEMENT dniS (#PCDATA)>

=== DAMnificado/marcas/Trabajo/trabajo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concurso SYSTEM "trabajodtd.dtd">
<concurso id="A01">
    <informacion>
      <sede>
        <direccion>Avenida de Galicia, 101, 36216 </direccion>
        <localidad>Vigo</localidad>
        <provincia>Pontevedra</provincia>
       </sede>
      <datos>
        <fechafin>Septiembre</fechafin>
        <edicion>Verano</edicion>
      </datos>
    </informacion>
    <participantes>
      <participacion cod = "EP022"> 
        <grupo nombre="El pshow" tipo="Rock-Rap">
            <integrante instrumento="Guitarra">
                <nombre>Gonzalo</nombre>
                <apellido>Gutierrez Otero</apellido>
                <dni>54785236J</dni>
            </integrante>
            <integrante instrumento="bateria">
                <nombre>Aron</nombre>
                <apellido>De Pedro Martinez</apellido>
                <dni>96535248W</dni>
            </integrante>
            <integrante> <!--vocal-->
                <nombre>David</nombre>
                <apellido>Carranque Rodriguez</apellido>
                <dni>54965874O</dni>
                <lider></lider>
            </integrante>
           </grupo>
      </participacion>
      <participacion cod="KM027">
        <solista>
          <integranteS instrumento="violin" tipo="clásica">
            <nombreS>Hector</nombreS>
            <apellidoS>Mascuñana Rodriguez</apellidoS>
            <dniS>54231414K</dniS>
            </integranteS>
          </solista>
      </participacion>
    </participantes>
    </concurso>
